<a href="https://colab.research.google.com/github/RaiqaRasool/ml_training/blob/main/6_Activation_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activation Functions
* **Learning Resource:**[Fundamentals of Deep Learning – Activation Functions and When to Use Them?](https://www.analyticsvidhya.com/blog/2020/01/fundamentals-deep-learning-activation-functions-when-to-use-them/)

Activation functions discussed:
1. Step function
2. Sigmoid
3. Tanh
4. ReLU
5. Softmax

## Step Function

In [ ]:
import numpy as np
def step_function(x):
  return np.where(x<0,0,1)

### Scalar

In [ ]:
input=torch.tensor(-1)
output=step_function(input)
output

array(0)

### Vector

In [ ]:
input=torch.randn(2)
output=step_function(input)
input,output

(tensor([-0.0344, -0.3003]), array([0, 0]))

### Tensor

In [ ]:
input=np.random.randn(3,3,4,5)
output=step_function(input)
input,output,output.shape

(array([[[[-2.13297234e-01,  8.45299540e-01,  1.49742115e+00,
           -1.53891842e+00,  6.22779806e-01],
          [ 8.11517085e-01, -1.28093489e+00, -8.50164337e-01,
            4.41293483e-01,  8.05472227e-01],
          [-7.87201727e-01,  3.74847559e-01, -4.36181978e-01,
           -5.69505621e-01,  4.27891432e-02],
          [-4.74572711e-01,  1.93140562e+00, -1.17311182e+00,
            1.12009862e+00,  1.91292300e+00]],
 
         [[ 1.25219583e+00, -3.24540430e-01, -5.84981798e-01,
            1.44169889e-03,  1.38996262e+00],
          [ 6.10201474e-01,  1.11650932e+00,  3.85295510e-01,
            6.79707357e-01, -5.20135618e-01],
          [-4.34282383e-01, -5.23943164e-01, -1.48347625e+00,
            1.24996181e+00,  3.69716433e-01],
          [-5.92047877e-01, -6.80181921e-02, -5.32708253e-01,
            3.85874368e-01,  1.83697945e-01]],
 
         [[-1.14885952e+00, -1.24971113e+00,  9.31027475e-01,
            1.31227864e+00, -4.80637257e-01],
          [-7.41140778

## Sigmoid Function
`output between 0 to 1`

In [ ]:
import torch
import torch.nn as nn

class SigmoidLayerModel(nn.Module):
  def __init__(self):
    super(SigmoidLayerModel,self).__init__()
    self.sigmoid=nn.Sigmoid()

  def forward(self,x):
    return self.sigmoid(x)

In [ ]:
model=SigmoidLayerModel()

### Scalar

In [ ]:
input_data=torch.tensor(-0.8)
output=model(input_data)
output

tensor(0.3100)

### Vector

In [ ]:
input_data=torch.randn(3)
output=model(input_data)
output

tensor([0.2351, 0.5074, 0.2663])

### Matrix

In [ ]:
input_data=torch.randn(4,4)
output=model(input_data)
input_data,output

(tensor([[ 0.3506, -0.8399,  1.8962,  1.9204],
         [ 0.1421, -0.0721, -0.5054, -2.1374],
         [-0.2603,  0.7422, -1.0005,  2.0600],
         [ 0.1540, -0.4799, -1.1484,  0.8390]]),
 tensor([[0.5868, 0.3015, 0.8695, 0.8722],
         [0.5355, 0.4820, 0.3763, 0.1055],
         [0.4353, 0.6775, 0.2688, 0.8870],
         [0.5384, 0.3823, 0.2408, 0.6983]]))

### Tensor

In [ ]:
input_data=torch.randn(2,3,2,2)
output=model(input_data)
output.shape,output

(torch.Size([2, 3, 2, 2]),
 tensor([[[[0.7227, 0.7755],
           [0.5237, 0.8011]],
 
          [[0.8002, 0.8407],
           [0.6966, 0.3041]],
 
          [[0.3224, 0.5900],
           [0.2798, 0.7505]]],
 
 
         [[[0.2112, 0.5457],
           [0.7609, 0.4307]],
 
          [[0.2455, 0.8455],
           [0.1140, 0.4283]],
 
          [[0.5487, 0.8631],
           [0.6662, 0.6322]]]]))

## Tanh Function
`output between -1 to 1`

In [ ]:
class TanhLayerModel(nn.Module):

  def __init__(self):
    super(TanhLayerModel,self).__init__()
    self.tanh=nn.Tanh()

  def forward(self,x):
    return self.tanh(x)

In [ ]:
model= TanhLayerModel()

### Tensor

In [ ]:
model(torch.randn(2,3,2,2))

tensor([[[[-0.7677, -0.1839],
          [ 0.0665, -0.2444]],

         [[-0.7136, -0.0379],
          [-0.2928,  0.9034]],

         [[-0.5396, -0.9656],
          [-0.3856, -0.9937]]],


        [[[ 0.8659, -0.5634],
          [-0.3280, -0.9861]],

         [[-0.5779, -0.0451],
          [ 0.8846,  0.8768]],

         [[-0.9559, -0.0377],
          [ 0.9924,  0.9838]]]])

## ReLU Function
`zero for -ve values and x given positive value x`

In [ ]:
import torch
import torch.nn as nn

class ReLULayerModel(nn.Module):
  def __init__(self):
    super(ReLULayerModel,self).__init__()
    self.relu=nn.ReLU()

  def forward(self,x):
    return self.relu(x)

In [ ]:
model=ReLULayerModel()

### Scalar

In [ ]:
model(torch.tensor(9))

tensor(9)

### Tensor

In [ ]:
model(torch.randn(2,3,2,2))

tensor([[[[1.9365, 0.0000],
          [0.2162, 0.0000]],

         [[0.0000, 0.6016],
          [0.0000, 1.1288]],

         [[0.0000, 0.0000],
          [0.8148, 0.0000]]],


        [[[0.5097, 0.0000],
          [1.0748, 1.1891]],

         [[0.8952, 0.2062],
          [0.5182, 0.3485]],

         [[0.8680, 0.0000],
          [0.3097, 0.0000]]]])

## Softmax Function
`input should have float values`

`not applied directly to the pixel values of image -- input.shape=(batch_size,num_classes) = 2D input`

In [ ]:
import torch
import torch.nn as nn

class SoftmaxLayerModel(nn.Module):
  def __init__(self):
    super(SoftmaxLayerModel,self).__init__()
    self.softmax_layer = nn.Softmax(dim=1)

  def forward(self,x):
    return self.softmax_layer(x)

In [ ]:
model=SoftmaxLayerModel()

When working with batched image data, the typical arrangement is that the batch size is the first dimension, and the class probabilities (for each image) are the second dimension. Therefore, you should usually set dim=1 (last dim) when applying softmax to batched image data.

### Single Data Point

In [ ]:
import torch
import torch.nn as nn

class SoftmaxScalarModel(nn.Module):
  def __init__(self):
    super(SoftmaxScalarModel,self).__init__()
    self.softmax_layer = nn.Softmax(dim=0) #dim set to zero as it is the only one in case of scalar

  def forward(self,x):
    return self.softmax_layer(x)

In [ ]:
model_scalar=SoftmaxScalarModel()
model_scalar(torch.tensor(10.)) # answer will always be one for scalar

tensor(1.)

In [ ]:
model_scalar(torch.tensor(100.))

tensor(1.)

#### Using SoftmaxLayerModel

In [ ]:
model(torch.randn(1,10))

tensor([[0.1123, 0.0348, 0.0281, 0.3448, 0.0594, 0.0307, 0.0247, 0.2457, 0.0668,
         0.0526]])

**Note:** In the context of neural networks for multi-class classification, it's common to represent even a single image's class scores as a 2D tensor with shape (1, num_classes) rather than using a scalar value. This consistent representation is used to ensure that the network can handle both single examples and batched examples without having to treat them differently.

Using a 2D tensor allows for uniform handling of input data, making it easier to generalize the network architecture and forward pass. Treating a single example as a (1, num_classes) tensor is conceptually simpler and avoids special cases when processing single examples.

While it's technically possible to use a scalar as input (i.e., a tensor with shape (1,) or just a single float), it's not the typical practice in multi-class classification with neural networks. Most frameworks, including PyTorch, expect inputs to be tensors with consistent dimensions, making it more practical to represent even single examples as (1, num_classes) tensors.

### Batch of 5 data points


In [ ]:
model(torch.randn(5,10)) # each row sum in output is 1

tensor([[0.0574, 0.0931, 0.0401, 0.1473, 0.0054, 0.0387, 0.2657, 0.0488, 0.2298,
         0.0737],
        [0.0105, 0.2445, 0.2005, 0.1247, 0.1096, 0.0629, 0.0536, 0.0961, 0.0808,
         0.0167],
        [0.0152, 0.0547, 0.4873, 0.0290, 0.0143, 0.0669, 0.0118, 0.0935, 0.0170,
         0.2104],
        [0.0450, 0.2133, 0.0324, 0.1698, 0.0764, 0.2187, 0.1282, 0.0846, 0.0168,
         0.0148],
        [0.0482, 0.0775, 0.0702, 0.2160, 0.0556, 0.0909, 0.2977, 0.0709, 0.0550,
         0.0181]])